### ISSUE TITLE
Fatal error after print.

### ISSUE THREAD

**Issue by tinypriest** [techfreek/OctoPrint-Friendlybeeper#17]
Garbagy plugin. Every print ends with a fatal error and I have to restart my Prusa MK3S and Octoprint. Plugin removed and everything is fine. Don't need "friendly beeps" that don't work, from dummy software guy. Sorry to offend; thanks anyway.

**Comment by techfreek** [comment]
I'm sorry to hear that. I've never seen this sort of error and I test with Octoprint+Prusa MK3S. Can you provide me some information on the version of Octoprint and Python you are using? Are you able to include Octoprint logs?

These would be incredibly helpful to fix this issue.

**Comment by tinypriest** [comment]
Sorry Alex for my unkind comment. 

I wasn't expecting that anyone would actually care about the problem! 

Am attaching 3 logs (pasted into DOCX)-- the first two logs were when I still had the plugin installed; the third is from today (plugin uninstalled).

[octoprint.log.2021-01-01.docx](https://github.com/techfreek/OctoPrint-Friendlybeeper/files/5791755/octoprint.log.2021-01-01.docx)
[octoprint.log.2021-01-02.docx](https://github.com/techfreek/OctoPrint-Friendlybeeper/files/5791756/octoprint.log.2021-01-02.docx)
[octoprint.log.2021-01-09.docx](https://github.com/techfreek/OctoPrint-Friendlybeeper/files/5791757/octoprint.log.2021-01-09.docx)

**Comment by techfreek** [comment]
I took a look at the attached logs, and I'll admit I'm not seeing anything related to this plugin. 

From octoprint.log.2021-01-01.docx, I saw
```
2021-01-02 10:10:12,593 - zeroconf - WARNING - Choked at offset 0 while unpacking b'\n\xba\x10\x00'
2021-01-02 10:10:12,594 - zeroconf - WARNING - Exception occurred:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/zeroconf/__init__.py", line 713, in __init__
    self.read_header()
  File "/home/pi/oprint/lib/python3.7/site-packages/zeroconf/__init__.py", line 736, in read_header
    ) = self.unpack(b'!6H')
  File "/home/pi/oprint/lib/python3.7/site-packages/zeroconf/__init__.py", line 723, in unpack
    info = struct.unpack(format_, self.data[self.offset : self.offset + length])
struct.error: unpack requires a buffer of 12 bytes
```
Which I believe is used by the core of octoprint, most likely guess based on what zeroconf is is something on the network sent an invalid message of some kind. Don't know enough to say much more than that.

From octoprint.log.2021-01-02.docx, I saw:
```
2021-01-02 14:47:03,474 - octoprint.util.comm - INFO - Changing monitoring state from "Starting" to "Printing"
2021-01-02 14:59:37,769 - octoprint.util.comm - WARNING - Received an error from the printer's firmware: HOTEND THERMAL RUNAWAY
| Last lines in terminal:
| Recv: NORMAL MODE: Percent done: 13; print time remaining in mins: 55
| Recv: SILENT MODE: Percent done: 14; print time remaining in mins: 55
| Recv: ok
| Send: N527 M73 P14 R54*17
| Recv: NORMAL MODE: Percent done: 14; print time remaining in mins: 54
| Recv: SILENT MODE: Percent done: 14; print time remaining in mins: 55
| Recv: ok
| Send: N528 G1 X181.061 Y81.128 E0.50346*84
| Recv: ok
| Send: N529 G1 X111.128 Y151.061 E34.03193*91
| Recv: ok
| Send: N530 G1 X109.665 Y151.061 E0.50346*111
| Recv: ok
| Send: N531 G1 X181.061 Y79.665 E34.74393*108
| Recv: echo:busy: processing
| Recv: ok
| Send: N532 M105*35
| Recv: ok T:232.0 /250.0 B:64.0 /63.0 T0:232.0 /250.0 @:127 B@:38 P:65.1 A:41.6
| Send: N533 G1 X181.061 Y78.202 E0.50346*83
| Recv: Error: HOTEND THERMAL RUNAWAY
2021-01-02 14:59:37,770 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Error: HOTEND THERMAL RUNAWAY"
2021-01-02 14:59:37,791 - octoprint.util.comm - INFO - Force-sending M112 to the printer
2021-01-02 14:59:37,825 - octoprint.util.comm - INFO - Changing monitoring state from "Error: HOTEND THERMAL RUNAWAY" to "Offline (Error: HOTEND THERMAL RUNAWAY)"
2021-01-02 14:59:37,870 - octoprint.plugins.action_command_notification - INFO - Notifications cleared
2021-01-02 14:59:38,378 - octoprint.plugins.FriendlyBeeper - INFO - Waiting for bed to cooldown
2021-01-02 14:59:38,380 - octoprint.plugins.FriendlyBeeper - INFO - Couldn't find printbed temperature
```
Looks like you had hotend thermal runaway at one point. I recently experienced that on my printer too. I think in my case the thermistor started to go back and incorrectly report. I ended up replacing mine. Yes, there was some logging from my plugin. The first line was to report status, the second was we detected an unusual state (the printer had disconnected at `2021-01-02 14:59:37,825`), and making note of that. It didn't bubble up to be an exception/error. 

I didn't see any errors in octoprint.log.2021-01-09.docx. 

At this point, I'm not sure if there is anything I can do to address the issues you are seeing. I'm not convinced they are caused by this plugin from what I am seeing.

**Comment by tinypriest** [comment]
Ok, thanks for having a look. I'll go through the remaining logs to see if the exception I experienced is captured there.
As for the thermal runaway error, that was actually to do with the hotend being cooled too much by the fan, so it was in fact a thermal reduction error in that the nozzle was getting too cold rather than too hot. I have a Volcano hotend and had to modify the fan shroud so that it was lower on the extruder assembly than the stock V6 nozzle, by about 8mm. But the shroud isn't a great design and still tends to cool the hotend along with the print. I don't like to print with the fan but sometimes it's necessary even with ABS for models that are too small for layers to cool quickly enough before the next pass. 
Anyway, thanks again and I'll see if there is anything in the other logs that might help.

Sent from Yahoo Mail for iPhone


On Saturday, January 9, 2021, 12:57 PM, Alex Bahm <notifications@github.com> wrote:




I took a look at the attached logs, and I'll admit I'm not seeing anything related to this plugin.

From octoprint.log.2021-01-01.docx, I saw
2021-01-02 10:10:12,593 - zeroconf - WARNING - Choked at offset 0 while unpacking b'\n\xba\x10\x00'
2021-01-02 10:10:12,594 - zeroconf - WARNING - Exception occurred:
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/zeroconf/__init__.py", line 713, in __init__
    self.read_header()
  File "/home/pi/oprint/lib/python3.7/site-packages/zeroconf/__init__.py", line 736, in read_header
    ) = self.unpack(b'!6H')
  File "/home/pi/oprint/lib/python3.7/site-packages/zeroconf/__init__.py", line 723, in unpack
    info = struct.unpack(format_, self.data[self.offset : self.offset + length])
struct.error: unpack requires a buffer of 12 bytes

Which I believe is used by the core of octoprint, most likely guess based on what zeroconf is is something on the network sent an invalid message of some kind. Don't know enough to say much more than that.

From octoprint.log.2021-01-02.docx, I saw:
2021-01-02 14:47:03,474 - octoprint.util.comm - INFO - Changing monitoring state from "Starting" to "Printing"
2021-01-02 14:59:37,769 - octoprint.util.comm - WARNING - Received an error from the printer's firmware: HOTEND THERMAL RUNAWAY
| Last lines in terminal:
| Recv: NORMAL MODE: Percent done: 13; print time remaining in mins: 55
| Recv: SILENT MODE: Percent done: 14; print time remaining in mins: 55
| Recv: ok
| Send: N527 M73 P14 R54*17
| Recv: NORMAL MODE: Percent done: 14; print time remaining in mins: 54
| Recv: SILENT MODE: Percent done: 14; print time remaining in mins: 55
| Recv: ok
| Send: N528 G1 X181.061 Y81.128 E0.50346*84
| Recv: ok
| Send: N529 G1 X111.128 Y151.061 E34.03193*91
| Recv: ok
| Send: N530 G1 X109.665 Y151.061 E0.50346*111
| Recv: ok
| Send: N531 G1 X181.061 Y79.665 E34.74393*108
| Recv: echo:busy: processing
| Recv: ok
| Send: N532 M105*35
| Recv: ok T:232.0 /250.0 B:64.0 /63.0 T0:232.0 /250.0 @:127 B@:38 P:65.1 A:41.6
| Send: N533 G1 X181.061 Y78.202 E0.50346*83
| Recv: Error: HOTEND THERMAL RUNAWAY
2021-01-02 14:59:37,770 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Error: HOTEND THERMAL RUNAWAY"
2021-01-02 14:59:37,791 - octoprint.util.comm - INFO - Force-sending M112 to the printer
2021-01-02 14:59:37,825 - octoprint.util.comm - INFO - Changing monitoring state from "Error: HOTEND THERMAL RUNAWAY" to "Offline (Error: HOTEND THERMAL RUNAWAY)"
2021-01-02 14:59:37,870 - octoprint.plugins.action_command_notification - INFO - Notifications cleared
2021-01-02 14:59:38,378 - octoprint.plugins.FriendlyBeeper - INFO - Waiting for bed to cooldown
2021-01-02 14:59:38,380 - octoprint.plugins.FriendlyBeeper - INFO - Couldn't find printbed temperature

Looks like you had hotend thermal runaway at one point. I recently experienced that on my printer too. I think in my case the thermistor started to go back and incorrectly report. I ended up replacing mine. Yes, there was some logging from my plugin. The first line was to report status, the second was we detected an unusual state (the printer had disconnected at 2021-01-02 14:59:37,825), and making note of that. It didn't bubble up to be an exception/error.

I didn't see any errors in octoprint.log.2021-01-09.docx.

At this point, I'm not sure if there is anything I can do to address the issues you are seeing. I'm not convinced they are caused by this plugin from what I am seeing.

**Comment by tinypriest** [comment]
Alex -- here is another log. I've highlighted in yellow where the error was happening (from timestamp "2021-01-04 16:17:24,775"). You'll see that the print ends, cool-down initiates, the FriendlyBeep plugin is called, and then there is some comm error and M112 is thrown. I also had trouble at other times when I wanted to cancel a print, which also was not possible with this plugin installed. Usually OctPrint can do this gracefully allowing you to then initiate a Z-axis lift once the cancel operation finishes. I think you can see this failed event elsewhere in the log. But the main problem is as highlighted in yellow, for when the print finishes and instead of getting a "beep", the printer calls an M112 firmware error.

[octoprint.log.2021-01-04.docx](https://github.com/techfreek/OctoPrint-Friendlybeeper/files/5791904/octoprint.log.2021-01-04.docx)

**Comment by techfreek** [comment]
Copying the log snippet so it is easier to view:
```
2021-01-04 16:17:24,777 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Finishing"
2021-01-04 16:17:24,798 - octoprint.printer.standard.job - INFO - Print job done - origin: local, path: Parametric_compartment_box_3x5comp_BOX_only_7.3x3.2x.3.65cm_1.2mm_wall_1.2vnoz_0.8_PLA.gcode, owner: [.....]
2021-01-04 16:17:24,804 - octoprint.plugins.FriendlyBeeper - INFO - Waiting for bed to cooldown
2021-01-04 16:17:24,831 - octoprint.plugins.FriendlyBeeper - INFO - Sent M300 S500 P5000 on event cool_down
2021-01-04 16:17:25,468 - octoprint.plugins.tracking - INFO - Sent tracking event print_done, payload: {'origin': 'local', 'file': '49ede38261cf45b3b8caf348334a2a54a2a8cc21', 'elapsed': 7953}
2021-01-04 16:17:33,264 - octoprint.util.comm - INFO - Communication timeout while printing, trying to trigger response from printer.
2021-01-04 16:17:33,277 - octoprint.util.comm - WARNING - Received line:
2021-01-04 16:17:33,281 - octoprint.util.comm - WARNING - | \x00start
2021-01-04 16:17:33,281 - octoprint.util.comm - WARNING - The received line contains at least one null byte character at position 0, this hints at some data corruption going on
2021-01-04 16:17:38,935 - octoprint.util.comm - WARNING - Printer requested line 1 but no sufficient history is available, can't resend. Printer requested line 1, current line is 6670, line history has 50 entries.
2021-01-04 16:17:38,937 - octoprint.util.comm - INFO - Changing monitoring state from "Finishing" to "Error: Printer requested line 1 but no sufficient history is available, can't resend"
2021-01-04 16:17:38,939 - octoprint.util.comm - INFO - Force-sending M112 to the printer
2021-01-04 16:17:38,981 - octoprint.util.comm - INFO - Changing monitoring state from "Error: Printer requested line 1 but no sufficient history is available, can't resend" to "Offline (Error: Printer requested line 1 but no sufficient history is available, can't resend)"
2021-01-04 16:17:38,991 - octoprint.util.comm - INFO - Got a resend request from the printer: requested line = 1, current line = 6673
| Last lines in terminal:
| Recv: echo: 3.9.1-3518
| Recv: echo: Last Updated: Sep 18 2020 17:05:06 | Author: (none, default config)
| Recv: Compiled: Sep 18 2020
| Recv: echo: Free Memory: 1746  PlannerBufferBytes: 1760
| Recv: echo:Stored settings retrieved
| Recv: adc_init
| Recv: Extruder fan type: NOCTUA
| Recv: CrashDetect ENABLED!
| Recv: FSensor ENABLED (sensor board revision: 0.3 or older)
| Recv: Sending 0xFF
| Recv: echo:SD init fail
| Recv: Error:Line Number is not Last Line Number+1, Last Line: 0
| Recv: Resend: 1
| Printer requested line 1 but no sufficient history is available, can't resend
| Changing monitoring state from "Finishing" to "Error: Printer requested line 1 but no sufficient history is available, can't resend"
| Send: M112
| Send: N6670 M112*22
| Send: N6671 M104 T0 S0*23
| Send: N6672 M140 S0*80
| Changing monitoring state from "Error: Printer requested line 1 but no sufficient history is available, can't resend" to "Offline (Error: Printer requested line 1 but no sufficient history is available, can't resend)"
```
This is very bizarre. I haven't seen this before. I did compare the output after the printer reinitialized, and it looks nearly identical to mine (after I manually sent an M112), so not sure why there would be a different. Not trying to discredit what you've seen, but I've also had a number of prints I've cancelled recently with no issues. So maybe there is something different between our environments. What other plugins do you have installed? Maybe there is some weird interop issue between this and a different plugin? In addition to this, I have:

- Action Command Notification Support
- Action Command Prompt Support
- Announcement Plugin
- Anonymous Usage Tracking
- Application Keys Plugin
- AstroPrint (1.6.3)
- Autoselect Plugin (0.3.0)
- Backup & Restore
- Backup Scheduler (1.0.0)
- Bed Visualizer (1.0.0)
- BetterHeaterTimeout (1.3.0)
- Core Wizard
- Cost Estimation (3.1.0)
- Dashboard (1.16.3)
- Discovery
- DisplayLayerProgress Plugin (1.24.0)
- Error Tracking
- Filament Manager (1.6.3)
- File Check (2020.8.7)
- Firmware Check (2020.9.23)
- Gcode Viewer
- Logging
- Pi Support Plugin
- PrinterAlerts (0.7.5)
- PrusaSlicer Thumbnails(0.1.3)
- Software Update
- Virtual Printer

I'll have to look closer to see if the minimal printer interaction this plugin has can trigger this sort of behavior. From what I'm reading. Maybe the timing of the send was unexpected? It's hard to know for sure.

1. Print finishes
2. Bed cooled down
3. Beep triggered
4. Octoprint detected timeout
5. Octoprint received corrupt line from printer
6. Printer requested resend of something from the beginning of the print, which octoprint couldn't do (history not that long)
7. Octoprint sent M112 due to the errors it received

I understand if you are unwilling to do this, but if you are willing to try something, the latest version of the plugin has a `Trigger Beep`  option to trigger it outside of printing to see if it reproduces frequently.

**Comment by tinypriest** [comment]
Sure, I would really like to use the plugin, actually. I'll update the plugin and see if there is any change, and send you a log so you can see. Will get to that tomorrow.

**Comment by tinypriest** [comment]
One other thing in the meantime, I set the actual beep time to 5000ms (5s), to increase the likelihood that I'll hear it when the print ends. I think I saw that the M112 error came up well into the beeping but before it should have finished, which made me think that the long beep interval prevented some other process to take place that may have timed out? That's pure guessing from just watching the error happen, and so it may be completely irrelevant to how things actually work but thought I would mention it.

**Comment by techfreek** [comment]
ooohhhhhhhhhhh that would do it. I just set mine to 5s and hit the "Trigger Beep" button, and caused the printer to reset. I'm guessing something about how it handles the m300 code causes it to think it's in an error state if it runs too long. I think the fix for that is just to create an upper limit on how long the beep can be (after some testing to make sure it's stable). 

Since that would prevent you from having a single beep that lasts 5 seconds, maybe you could find one of the songs written in M300 codes to make up for that?

**Comment by tinypriest** [comment]
Ok! I'll give that a try. Sure, a little melody would work for me to get through the background noise of my house at any one time. Thanks.

**Comment by techfreek** [comment]
Turns out this is a known issue on the prusa firmware: https://github.com/prusa3d/Prusa-Firmware/issues/2045
I'll see if I can get a fix out for this (in the scope of this plugin) today

**Comment by techfreek** [comment]
Reopening until this is released

**Comment by techfreek** [comment]
If you want to try it out before I publish a new release, you can install from https://github.com/techfreek/OctoPrint-Friendlybeeper/archive/development.zip
And that should have a fix for the issue you were seeing (it also enforces that any old settings will be updated to ensure they dont cause issues)

**Comment by tinypriest** [comment]
I'll give it a try and let you know.

**Comment by tinypriest** [comment]
Yikes, well there's still a problem. 

1) I first did a test where I cancelled the print to see if it would do it gracefully. It beeped and the print stopped, but then a strange thing kept happening where OctoPrint never let me click the Z-lift and instead re-energized the nozzle and bed heaters, then beeped when they reached the set temps, then repeated. Here's a screen grab of the process. You'll see the flat line in there before it did it again -- that was actually after I restarted the printer; it just kept doing it until I disconnected the connection through OctoPrint.

![Beeper_cancel_repeating_01](https://user-images.githubusercontent.com/49359824/104134415-322fc000-533e-11eb-9500-11d781f1378d.jpg)

2) The second test was to let a short print finish. That seemed to go ok except that the printer reset and I got this message from OctoPrint to inform me:

![Beeper_cancel_repeating_02](https://user-images.githubusercontent.com/49359824/104134437-55f30600-533e-11eb-8fd5-70f2f80e0f66.jpg)

**Comment by tinypriest** [comment]
Here is the latest log:

[octoprint.log.2021-01-10.txt](https://github.com/techfreek/OctoPrint-Friendlybeeper/files/5793263/octoprint.log.2021-01-10.txt)

**Comment by tinypriest** [comment]
Correction: -- in 1) it kept doing it until I restarted the RPi.

**Comment by techfreek** [comment]
My apologies, I should have clarified that with the changes I made, you have to open and save the settings (regardless of if you made any) so that it will reset the duration to be shorter. (I mention this because it is still triggering a 5 second beep)

I'm unable to fix the Prusa firmware to handle the long beep, but I am able to set a cap on how long the beep is. If need be, I can make an additional change to not require a config change, but I didn't think that was necessary.

**Comment by tinypriest** [comment]
No problem -- I did see that the beep duration seemed to be capped at 3500ms after I tried changing it to 5000ms. After I saved the settings, I saw that it was back to 3500ms. So I'm pretty sure I had everything saved again with the shorter duration before printing. But I guess until there's some fix from Prusa's crew it would be good to know what the max beep duration is? I assumed you had maybe done that and figured it was 3500ms.

**Comment by techfreek** [comment]
Oh. Looks you can still enter a higher value and it will take it. I'll have to fix that.

I'll make sure I add some data verification to this since you can enter an invalid value. I did some testing and found that 5 seconds caused the issue, but not 4 seconds. I did 3.5 just as a precaution.

**Comment by techfreek** [comment]
Okay, should be fixed now. Actual data verification was added, and it will warn if the value is outside of those bounds, and set to a valid value.

**Comment by techfreek** [comment]
Released with v0.4.1. If you still have issues, feel free to open a new issue

**Comment by Jaxx005** [comment]
@techfreek 

Hi there! Did that M300 beep fix reach public release?   I am still having the "M300 P5000 S0" code reset the MK3S main board.

See recent post(s) on link above.
RE: https://github.com/prusa3d/Prusa-Firmware/issues/2045#issuecomment-981176464

FYI: the 'dwell' and 'pause print' commands shows a LCD message, thus overwriting any user-code display.  So "M300 P5000 S0" gets round this, but also is useful for pause during an alarm (e.g. short 'pip' every 5sec, as a reminder alarm).   Thanks.

**Comment by techfreek** [comment]
@Jaxx005 this plugin has a "fix" that makes it harder to hit the issue, but the real issue is in Prusa Firmware. Basically the issue is that a M300 in prusa firmware is implemented as a blocking operation (so nothing else occurs on the mainboard). This eventually gets detected either by Prusa Firmware/Octoprint as a potential issue because it seems like the system has hung, so it throws a fatal error.
The change in this repo is just to warn and make it harder for someone to enter a long M300 command.
In the meantime, you'd be best of just splitting the M300 beep into 2 commands:
```
M300 P2500 S0
M300 P2500 S0
```

**Comment by Jaxx005** [comment]
Thanks all. I used the DWELL command instead, which seems to work, so I assume is non-blocking etc.   Downside, is that it overwrites the text display with “Sleeping…” (as does the ‘PAUSE PRINT’ gcode) .  So multiple M300 P2500 S0 commands might be better option, as the LCD message would be retained.  Perhaps hard-limiting (capping) the period to 2500 is possible in the FW, at least to avoid a reboot? 😊

 

Note: my original goal was “warning alarm sounds” + “message” + “pause print” + “reminder alarm sounds”

TTFN
